source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

use_frameworks!

target 'MarketPlace' do
	pod 'Alamofire'
    pod 'BEMCheckBox'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'
	pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'DateTools'
    pod 'HCSStarRatingView'
    pod 'Socket.IO-Client-Swift'
    pod 'SlackTextViewController'
    pod 'LoremIpsum'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'FSCalendar'
    pod 'SAMKeychain'
end
